version: '3'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - ".:/om30-test"
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_user
      POSTGRES_DB: om30_test
    ports:
    - "5432:5432"
