version: '3'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: data_base_user
      POSTGRES_PASSWORD: data_base_user
      POSTGRES_DB: om30-test

volumes:
  postgres_data:
