default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: database_user
  password: database_user
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: om30_test_development

test:
  <<: *default
  database: om30_test_test

production:
  <<: *default
  database: om30_test_production
  username: om30_test
  password: <%= ENV["OM30_TEST_DATABASE_PASSWORD"] %>
